export const PLAID_CLIENT_ID = 'PLAID_CLIENT_ID';
export const PLAID_SECRET = 'PLAID_SECRET';
export const PLAID_ACCESS_TOKEN='PLAID_ACCESS_TOKEN';
export const PLAID_PUBLIC_TOKEN='PLAID_PUBLIC_TOKEN';
export const PLAID_API_BASE='PLAID_API_BASE';